title: Bar Aberto
description: comunidade informal, transparente e aberta de promoção de tecnologias, metodologias, experiências, conhecimento em **código aberto** para Angola e o mundo
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
